/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApprovalEntry {
  'endHour' : string,
  'icName' : string,
  'createdByUserId' : bigint,
  'exclusionDate' : string,
  'entryId' : bigint,
  'timestampNs' : bigint,
  'startHour' : string,
  'managerName' : string,
}
export interface DailyRecord {
  'cap' : bigint,
  'approvals' : Array<ApprovalEntry>,
}
export interface DaySummary {
  'cap' : bigint,
  'countApproved' : bigint,
  'date' : string,
  'icNames' : Array<string>,
}
export interface HourlyLimit { 'limit' : bigint, 'periodIndex' : bigint }
export type R = { 'ok' : UserInfo } |
  { 'err' : string };
export type R_1 = { 'ok' : null } |
  { 'err' : string };
export type R_2 = { 'ok' : bigint } |
  { 'err' : string };
export type R_3 = { 'ok' : string } |
  { 'err' : string };
export type R_4 = { 'ok' : ApprovalEntry } |
  { 'err' : string };
export interface SlotUsage { 'count' : bigint, 'timeSlot' : string }
export interface SlotUsageWithLimit {
  'count' : bigint,
  'limit' : bigint,
  'timeSlot' : string,
}
export interface UserInfo {
  'userId' : bigint,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  'addApproval' : ActorMethod<
    [string, string, string, string, string, string],
    R_4
  >,
  'deleteUser' : ActorMethod<[string, bigint], R_1>,
  'getCallerUserId' : ActorMethod<[string], [] | [bigint]>,
  'getCallerUserProfile' : ActorMethod<[string], [] | [UserProfile]>,
  'getDailyApprovals' : ActorMethod<[string], Array<ApprovalEntry>>,
  'getDailyCap' : ActorMethod<[string], bigint>,
  'getFutureApprovals' : ActorMethod<[string], Array<ApprovalEntry>>,
  'getHistory' : ActorMethod<
    [string, [] | [string], [] | [string]],
    Array<[string, DailyRecord]>
  >,
  'getHourlyLimits' : ActorMethod<[string], Array<HourlyLimit>>,
  'getRemainingSlots' : ActorMethod<[string], bigint>,
  'getSlotUsage' : ActorMethod<[string], Array<SlotUsage>>,
  'getSlotUsageWithLimits' : ActorMethod<[string], Array<SlotUsageWithLimit>>,
  'getSummary' : ActorMethod<[string], Array<DaySummary>>,
  'isCallerAdmin' : ActorMethod<[string], boolean>,
  'listAllUsers' : ActorMethod<[string], Array<UserInfo>>,
  'login' : ActorMethod<[string, string], R_3>,
  'logout' : ActorMethod<[string], undefined>,
  'register' : ActorMethod<[string, string], R_2>,
  'removeApproval' : ActorMethod<[string, bigint], R_1>,
  'setDailyCap' : ActorMethod<[string, bigint], R_1>,
  'setHourlyLimit' : ActorMethod<[string, bigint, bigint], R_1>,
  'setUserRole' : ActorMethod<[string, bigint, UserRole], R_1>,
  'whoami' : ActorMethod<[string], R>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];