/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApprovalEntry = IDL.Record({
  'endHour' : IDL.Text,
  'icName' : IDL.Text,
  'createdByUserId' : IDL.Nat,
  'exclusionDate' : IDL.Text,
  'entryId' : IDL.Nat,
  'timestampNs' : IDL.Int,
  'startHour' : IDL.Text,
  'managerName' : IDL.Text,
});
export const R_4 = IDL.Variant({ 'ok' : ApprovalEntry, 'err' : IDL.Text });
export const R_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyRecord = IDL.Record({
  'cap' : IDL.Nat,
  'approvals' : IDL.Vec(ApprovalEntry),
});
export const HourlyLimit = IDL.Record({
  'limit' : IDL.Nat,
  'periodIndex' : IDL.Nat,
});
export const SlotUsage = IDL.Record({
  'count' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const SlotUsageWithLimit = IDL.Record({
  'count' : IDL.Nat,
  'limit' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const DaySummary = IDL.Record({
  'cap' : IDL.Nat,
  'countApproved' : IDL.Nat,
  'date' : IDL.Text,
  'icNames' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserInfo = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
});
export const R_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const R_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const R = IDL.Variant({ 'ok' : UserInfo, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'addApproval' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [R_4],
      [],
    ),
  'deleteUser' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
  'getCallerUserId' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getDailyApprovals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ApprovalEntry)],
      ['query'],
    ),
  'getDailyCap' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getFutureApprovals' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ApprovalEntry)],
      ['query'],
    ),
  'getHistory' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyRecord))],
      ['query'],
    ),
  'getHourlyLimits' : IDL.Func([IDL.Text], [IDL.Vec(HourlyLimit)], ['query']),
  'getRemainingSlots' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getSlotUsage' : IDL.Func([IDL.Text], [IDL.Vec(SlotUsage)], ['query']),
  'getSlotUsageWithLimits' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SlotUsageWithLimit)],
      ['query'],
    ),
  'getSummary' : IDL.Func([IDL.Text], [IDL.Vec(DaySummary)], ['query']),
  'isCallerAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserInfo)], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [R_3], []),
  'logout' : IDL.Func([IDL.Text], [], []),
  'register' : IDL.Func([IDL.Text, IDL.Text], [R_2], []),
  'removeApproval' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
  'setDailyCap' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
  'setHourlyLimit' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [R_1], []),
  'setUserRole' : IDL.Func([IDL.Text, IDL.Nat, UserRole], [R_1], []),
  'whoami' : IDL.Func([IDL.Text], [R], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApprovalEntry = IDL.Record({
    'endHour' : IDL.Text,
    'icName' : IDL.Text,
    'createdByUserId' : IDL.Nat,
    'exclusionDate' : IDL.Text,
    'entryId' : IDL.Nat,
    'timestampNs' : IDL.Int,
    'startHour' : IDL.Text,
    'managerName' : IDL.Text,
  });
  const R_4 = IDL.Variant({ 'ok' : ApprovalEntry, 'err' : IDL.Text });
  const R_1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyRecord = IDL.Record({
    'cap' : IDL.Nat,
    'approvals' : IDL.Vec(ApprovalEntry),
  });
  const HourlyLimit = IDL.Record({
    'limit' : IDL.Nat,
    'periodIndex' : IDL.Nat,
  });
  const SlotUsage = IDL.Record({ 'count' : IDL.Nat, 'timeSlot' : IDL.Text });
  const SlotUsageWithLimit = IDL.Record({
    'count' : IDL.Nat,
    'limit' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const DaySummary = IDL.Record({
    'cap' : IDL.Nat,
    'countApproved' : IDL.Nat,
    'date' : IDL.Text,
    'icNames' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserInfo = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  const R_3 = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const R_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const R = IDL.Variant({ 'ok' : UserInfo, 'err' : IDL.Text });
  
  return IDL.Service({
    'addApproval' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [R_4],
        [],
      ),
    'deleteUser' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
    'getCallerUserId' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getDailyApprovals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ApprovalEntry)],
        ['query'],
      ),
    'getDailyCap' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getFutureApprovals' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ApprovalEntry)],
        ['query'],
      ),
    'getHistory' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyRecord))],
        ['query'],
      ),
    'getHourlyLimits' : IDL.Func([IDL.Text], [IDL.Vec(HourlyLimit)], ['query']),
    'getRemainingSlots' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getSlotUsage' : IDL.Func([IDL.Text], [IDL.Vec(SlotUsage)], ['query']),
    'getSlotUsageWithLimits' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SlotUsageWithLimit)],
        ['query'],
      ),
    'getSummary' : IDL.Func([IDL.Text], [IDL.Vec(DaySummary)], ['query']),
    'isCallerAdmin' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([IDL.Text], [IDL.Vec(UserInfo)], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [R_3], []),
    'logout' : IDL.Func([IDL.Text], [], []),
    'register' : IDL.Func([IDL.Text, IDL.Text], [R_2], []),
    'removeApproval' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
    'setDailyCap' : IDL.Func([IDL.Text, IDL.Nat], [R_1], []),
    'setHourlyLimit' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [R_1], []),
    'setUserRole' : IDL.Func([IDL.Text, IDL.Nat, UserRole], [R_1], []),
    'whoami' : IDL.Func([IDL.Text], [R], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };