/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApprovalEntry = IDL.Record({
  'endHour' : IDL.Text,
  'icName' : IDL.Text,
  'entryId' : IDL.Nat,
  'timestampNs' : IDL.Int,
  'startHour' : IDL.Text,
  'managerName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyRecord = IDL.Record({
  'cap' : IDL.Nat,
  'approvals' : IDL.Vec(ApprovalEntry),
});
export const HourlyLimit = IDL.Record({
  'limit' : IDL.Nat,
  'periodIndex' : IDL.Nat,
});
export const SlotUsage = IDL.Record({
  'count' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const SlotUsageWithLimit = IDL.Record({
  'count' : IDL.Nat,
  'limit' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const DaySummary = IDL.Record({
  'cap' : IDL.Nat,
  'countApproved' : IDL.Nat,
  'date' : IDL.Text,
  'icNames' : IDL.Vec(IDL.Text),
});
export const UserInfo = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addApproval' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [ApprovalEntry],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyApprovals' : IDL.Func([], [IDL.Vec(ApprovalEntry)], ['query']),
  'getDailyCap' : IDL.Func([], [IDL.Nat], ['query']),
  'getHistory' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Vec(IDL.Tuple(IDL.Text, DailyRecord))],
      ['query'],
    ),
  'getHourlyLimits' : IDL.Func([], [IDL.Vec(HourlyLimit)], ['query']),
  'getRemainingSlots' : IDL.Func([], [IDL.Nat], ['query']),
  'getSlotUsage' : IDL.Func([], [IDL.Vec(SlotUsage)], ['query']),
  'getSlotUsageWithLimits' : IDL.Func(
      [],
      [IDL.Vec(SlotUsageWithLimit)],
      ['query'],
    ),
  'getSummary' : IDL.Func([], [IDL.Vec(DaySummary)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
  'removeApproval' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setDailyCap' : IDL.Func([IDL.Nat], [], []),
  'setHourlyLimit' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApprovalEntry = IDL.Record({
    'endHour' : IDL.Text,
    'icName' : IDL.Text,
    'entryId' : IDL.Nat,
    'timestampNs' : IDL.Int,
    'startHour' : IDL.Text,
    'managerName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyRecord = IDL.Record({
    'cap' : IDL.Nat,
    'approvals' : IDL.Vec(ApprovalEntry),
  });
  const HourlyLimit = IDL.Record({
    'limit' : IDL.Nat,
    'periodIndex' : IDL.Nat,
  });
  const SlotUsage = IDL.Record({ 'count' : IDL.Nat, 'timeSlot' : IDL.Text });
  const SlotUsageWithLimit = IDL.Record({
    'count' : IDL.Nat,
    'limit' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const DaySummary = IDL.Record({
    'cap' : IDL.Nat,
    'countApproved' : IDL.Nat,
    'date' : IDL.Text,
    'icNames' : IDL.Vec(IDL.Text),
  });
  const UserInfo = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addApproval' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [ApprovalEntry],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyApprovals' : IDL.Func([], [IDL.Vec(ApprovalEntry)], ['query']),
    'getDailyCap' : IDL.Func([], [IDL.Nat], ['query']),
    'getHistory' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Vec(IDL.Tuple(IDL.Text, DailyRecord))],
        ['query'],
      ),
    'getHourlyLimits' : IDL.Func([], [IDL.Vec(HourlyLimit)], ['query']),
    'getRemainingSlots' : IDL.Func([], [IDL.Nat], ['query']),
    'getSlotUsage' : IDL.Func([], [IDL.Vec(SlotUsage)], ['query']),
    'getSlotUsageWithLimits' : IDL.Func(
        [],
        [IDL.Vec(SlotUsageWithLimit)],
        ['query'],
      ),
    'getSummary' : IDL.Func([], [IDL.Vec(DaySummary)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserInfo)], ['query']),
    'removeApproval' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setDailyCap' : IDL.Func([IDL.Nat], [], []),
    'setHourlyLimit' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'setUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  });
};

export const init = ({ IDL }) => { return []; };