/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApprovalEntry {
  'endHour' : string,
  'icName' : string,
  'entryId' : bigint,
  'timestampNs' : bigint,
  'startHour' : string,
  'managerName' : string,
}
export interface DailyRecord {
  'cap' : bigint,
  'approvals' : Array<ApprovalEntry>,
}
export interface DaySummary {
  'cap' : bigint,
  'countApproved' : bigint,
  'date' : string,
  'icNames' : Array<string>,
}
export interface HourlyLimit { 'limit' : bigint, 'periodIndex' : bigint }
export interface SlotUsage { 'count' : bigint, 'timeSlot' : string }
export interface SlotUsageWithLimit {
  'count' : bigint,
  'limit' : bigint,
  'timeSlot' : string,
}
export interface UserInfo {
  'principal' : Principal,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addApproval' : ActorMethod<[string, string, string, string], ApprovalEntry>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyApprovals' : ActorMethod<[], Array<ApprovalEntry>>,
  'getDailyCap' : ActorMethod<[], bigint>,
  'getHistory' : ActorMethod<
    [[] | [string], [] | [string]],
    Array<[string, DailyRecord]>
  >,
  'getHourlyLimits' : ActorMethod<[], Array<HourlyLimit>>,
  'getRemainingSlots' : ActorMethod<[], bigint>,
  'getSlotUsage' : ActorMethod<[], Array<SlotUsage>>,
  'getSlotUsageWithLimits' : ActorMethod<[], Array<SlotUsageWithLimit>>,
  'getSummary' : ActorMethod<[], Array<DaySummary>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserInfo>>,
  'removeApproval' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setDailyCap' : ActorMethod<[bigint], undefined>,
  'setHourlyLimit' : ActorMethod<[bigint, bigint], undefined>,
  'setUserRole' : ActorMethod<[Principal, UserRole], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];