/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/main.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HourlyLimit {
    limit: bigint;
    periodIndex: bigint;
}
export type R = {
    __kind__: "ok";
    ok: UserInfo;
} | {
    __kind__: "err";
    err: string;
};
export type R_4 = {
    __kind__: "ok";
    ok: ApprovalEntry;
} | {
    __kind__: "err";
    err: string;
};
export interface DailyRecord {
    cap: bigint;
    approvals: Array<ApprovalEntry>;
}
export interface ApprovalEntry {
    endHour: string;
    icName: string;
    createdByUserId: bigint;
    exclusionDate: string;
    entryId: bigint;
    timestampNs: bigint;
    startHour: string;
    managerName: string;
}
export type R_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface UserInfo {
    userId: bigint;
    name: string;
    role: UserRole;
}
export type R_2 = {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
};
export interface DaySummary {
    cap: bigint;
    countApproved: bigint;
    date: string;
    icNames: Array<string>;
}
export interface SlotUsage {
    count: bigint;
    timeSlot: string;
}
export interface SlotUsageWithLimit {
    count: bigint;
    limit: bigint;
    timeSlot: string;
}
export type R_3 = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface mainInterface {
    addApproval(sessionToken: string, icName: string, managerName: string, startHour: string, endHour: string, exclusionDate: string): Promise<R_4>;
    deleteUser(sessionToken: string, targetUserId: bigint): Promise<R_1>;
    getCallerUserId(sessionToken: string): Promise<bigint | null>;
    getCallerUserProfile(sessionToken: string): Promise<UserProfile | null>;
    getDailyApprovals(sessionToken: string): Promise<Array<ApprovalEntry>>;
    getDailyCap(sessionToken: string): Promise<bigint>;
    getFutureApprovals(sessionToken: string): Promise<Array<ApprovalEntry>>;
    getHistory(sessionToken: string, startDate: string | null, endDate: string | null): Promise<Array<[string, DailyRecord]>>;
    getHourlyLimits(sessionToken: string): Promise<Array<HourlyLimit>>;
    getRemainingSlots(sessionToken: string): Promise<bigint>;
    getSlotUsage(sessionToken: string): Promise<Array<SlotUsage>>;
    getSlotUsageWithLimits(sessionToken: string): Promise<Array<SlotUsageWithLimit>>;
    getSummary(sessionToken: string): Promise<Array<DaySummary>>;
    isCallerAdmin(sessionToken: string): Promise<boolean>;
    listAllUsers(sessionToken: string): Promise<Array<UserInfo>>;
    login(username: string, password: string): Promise<R_3>;
    logout(sessionToken: string): Promise<void>;
    register(username: string, password: string): Promise<R_2>;
    removeApproval(sessionToken: string, entryId: bigint): Promise<R_1>;
    setDailyCap(sessionToken: string, cap: bigint): Promise<R_1>;
    setHourlyLimit(sessionToken: string, periodIndex: bigint, limit: bigint): Promise<R_1>;
    setUserRole(sessionToken: string, targetUserId: bigint, role: UserRole): Promise<R_1>;
    whoami(sessionToken: string): Promise<R>;
}
import type { ApprovalEntry as _ApprovalEntry, R as _R, R_1 as _R_1, R_2 as _R_2, R_3 as _R_3, R_4 as _R_4, UserInfo as _UserInfo, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/main.did.d.ts";
export class Main implements mainInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addApproval(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<R_4> {
        if (this.processError) {
            try {
                const result = await this.actor.addApproval(arg0, arg1, arg2, arg3, arg4, arg5);
                return from_candid_R_4_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addApproval(arg0, arg1, arg2, arg3, arg4, arg5);
            return from_candid_R_4_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteUser(arg0: string, arg1: bigint): Promise<R_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserId(arg0: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserId(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserId(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(arg0: string): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyApprovals(arg0: string): Promise<Array<ApprovalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyApprovals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyApprovals(arg0);
            return result;
        }
    }
    async getDailyCap(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyCap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyCap(arg0);
            return result;
        }
    }
    async getFutureApprovals(arg0: string): Promise<Array<ApprovalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFutureApprovals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFutureApprovals(arg0);
            return result;
        }
    }
    async getHistory(arg0: string, arg1: string | null, arg2: string | null): Promise<Array<[string, DailyRecord]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistory(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistory(arg0, to_candid_opt_n7(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n7(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getHourlyLimits(arg0: string): Promise<Array<HourlyLimit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHourlyLimits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHourlyLimits(arg0);
            return result;
        }
    }
    async getRemainingSlots(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRemainingSlots(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRemainingSlots(arg0);
            return result;
        }
    }
    async getSlotUsage(arg0: string): Promise<Array<SlotUsage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotUsage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotUsage(arg0);
            return result;
        }
    }
    async getSlotUsageWithLimits(arg0: string): Promise<Array<SlotUsageWithLimit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSlotUsageWithLimits(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSlotUsageWithLimits(arg0);
            return result;
        }
    }
    async getSummary(arg0: string): Promise<Array<DaySummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary(arg0);
            return result;
        }
    }
    async isCallerAdmin(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin(arg0);
            return result;
        }
    }
    async listAllUsers(arg0: string): Promise<Array<UserInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async login(arg0: string, arg1: string): Promise<R_3> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_R_3_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_R_3_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async logout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logout(arg0);
            return result;
        }
    }
    async register(arg0: string, arg1: string): Promise<R_2> {
        if (this.processError) {
            try {
                const result = await this.actor.register(arg0, arg1);
                return from_candid_R_2_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(arg0, arg1);
            return from_candid_R_2_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeApproval(arg0: string, arg1: bigint): Promise<R_1> {
        if (this.processError) {
            try {
                const result = await this.actor.removeApproval(arg0, arg1);
                return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeApproval(arg0, arg1);
            return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setDailyCap(arg0: string, arg1: bigint): Promise<R_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setDailyCap(arg0, arg1);
                return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setDailyCap(arg0, arg1);
            return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setHourlyLimit(arg0: string, arg1: bigint, arg2: bigint): Promise<R_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setHourlyLimit(arg0, arg1, arg2);
                return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setHourlyLimit(arg0, arg1, arg2);
            return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserRole(arg0: string, arg1: bigint, arg2: UserRole): Promise<R_1> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserRole(arg0, arg1, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserRole(arg0, arg1, to_candid_UserRole_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_R_1_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async whoami(arg0: string): Promise<R> {
        if (this.processError) {
            try {
                const result = await this.actor.whoami(arg0);
                return from_candid_R_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.whoami(arg0);
            return from_candid_R_n19(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_R_1_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _R_1): R_1 {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_R_2_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _R_2): R_2 {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_R_3_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _R_3): R_3 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_R_4_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _R_4): R_4 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_R_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _R): R {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserInfo_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserInfo): UserInfo {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: bigint;
    name: string;
    role: _UserRole;
}): {
    userId: bigint;
    name: string;
    role: UserRole;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_UserRole_n11(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ApprovalEntry;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ApprovalEntry;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserInfo_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserInfo>): Array<UserInfo> {
    return value.map((x)=>from_candid_UserInfo_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Main {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Main(actor, _uploadFile, _downloadFile, options.processError);
}
